Cell 1 : Import Libraries
-

In [1]:
import pandas as pd 
import numpy as numpy

from sklearn.feature_extraction.text import TfidfVectorizer

Cell 2 : Load Data
-

In [2]:
df = pd.read_csv("../data/processed_jobs.csv")

df.head()

   job_id  ...                                      combined_text
0       1  ...  software engineerour company growth fast paced...
1       2  ...  content writerour company fast paced opportuni...
2       3  ...  customer support specialistwe global innovatio...
3       4  ...  data analystour company fast paced support tea...
4       5  ...  graphic designerwe global experience skills pr...

[5 rows x 26 columns]

Cell 3 - Check Missing Values

In [3]:
df.isnull().sum()

job_id                          0
job_title                       0
job_description                 0
requirements                    0
benefits                        0
company_name                 1472
company_profile                 0
industry                        0
employment_type                 0
location                        0
salary_range                    0
required_experience_years       0
education_level                 0
department                      0
posting_date                    0
application_deadline            0
contact_email                   0
company_website              1472
has_logo                        0
num_open_positions              0
job_function                    0
telecommuting                   0
fraud_reason                 1528
text_length                     0
is_fake                         0
combined_text                   0
dtype: int64

Cell 4 - Select Structured Features
-

In [4]:
structured_cols = [
    "required_experience_years",
    "num_open_positions",
    "has_logo",
    "telecommuting"
]

df[structured_cols].head()

   required_experience_years  num_open_positions  has_logo  telecommuting
0                          8                   3         0              0
1                         10                  10         0              1
2                          3                   6         0              0
3                         10                   4         1              1
4                          7                   5         0              0

Cell 5 - Fill Missing Values
-

In [5]:
df["required_experience_years"] = df["required_experience_years"].fillna(0)

df["num_open_positions"] = df["num_open_positions"].fillna(1)

df["has_logo"] = df["has_logo"].fillna(0)

df["telecommuting"] = df["telecommuting"].fillna(0)

Cell 6 - Convert Yes/No Columns 
-

In [6]:
df["has_logo"].unique()

array([0, 1])

Cell 7 - Scale Numerical Features 
-

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

numeric_features = scaler.fit_transform(
    df[structured_cols]
)

Cell 8 - TF-IDF
-

In [8]:
tfidf = TfidfVectorizer(
    max_features=6000,
    ngram_range=(1,2),
    stop_words="english"
)

text_features = tfidf.fit_transform(
    df["combined_text"]
)

Cell 9 - Combine Text + Structured Features 
-

In [9]:
from scipy.sparse import hstack 

X = hstack([
    text_features,
    numeric_features
])

y = df["is_fake"]

Cell 10 - Train/Test Split
-

In [10]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

Cell 11 - Save Feature Objects
-

In [11]:
import pickle

pickle.dump(
    tfidf,
    open("../models/tfidf.pkl","wb")

)

pickle.dump(
    scaler,
    open("../models/scaler.pkl","wb")
)

In [12]:
print(text_features.shape)
print(numeric_features.shape)
print(X.shape)

(3000, 5480)
(3000, 4)
(3000, 5484)